version: '3'
services:
  mininet:
    image: sdn-base
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/lib/modules:/lib/modules"
      - "${PWD}/src:/opt"
    environment:
      - DISPLAY=${DISPLAY}
